//! Stepped-parameter enums for every discrete control on the Minilogue XD.
//!
//! Each enum is generated by the `stepped_param_enum!` macro, which
//! produces the [`SteppedParam`] implementation, `TryFrom<u8>`, and
//! `Display`.

use std::fmt;

use crate::error::{Error, Result};
use crate::param::SteppedParam;

// ---------------------------------------------------------------------------
// Macro
// ---------------------------------------------------------------------------

/// Generates a stepped-parameter enum with full TX/RX/program round-tripping.
///
/// # Syntax
///
/// ```text
/// stepped_param_enum! {
///     /// Doc comment
///     EnumName {
///         Variant1 => { tx: 0, rx: 0..=63, prog: 0, display: "custom" },
///         Variant2 => { tx: 127, rx: 64..=127, prog: 1 },
///     }
/// }
/// ```
///
/// If `display` is omitted, the variant identifier is used.
macro_rules! stepped_param_enum {
    (
        $( #[doc = $enum_doc:literal] )*
        $name:ident {
            $(
                $( #[doc = $var_doc:literal] )*
                $variant:ident => {
                    tx: $tx:expr,
                    rx: $rx_lo:literal ..= $rx_hi:literal,
                    prog: $prog:expr
                    $(, display: $disp:literal)?
                }
            ),+ $(,)?
        }
    ) => {
        $( #[doc = $enum_doc] )*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        #[non_exhaustive]
        pub enum $name {
            $(
                $( #[doc = $var_doc] )*
                $variant,
            )+
        }

        impl SteppedParam for $name {
            fn to_tx_value(&self) -> u8 {
                match self {
                    $( Self::$variant => $tx, )+
                }
            }

            fn from_rx_value(v: u8) -> Result<Self> {
                match v {
                    $( $rx_lo ..= $rx_hi => Ok(Self::$variant), )+
                    _ => Err(Error::OutOfRange {
                        type_name: stringify!($name),
                        value: i64::from(v),
                        min: 0,
                        max: 127,
                    }),
                }
            }

            fn to_program_value(&self) -> u8 {
                match self {
                    $( Self::$variant => $prog, )+
                }
            }

            fn from_program_value(v: u8) -> Result<Self> {
                match v {
                    $( x if x == $prog => Ok(Self::$variant), )+
                    _ => Err(Error::OutOfRange {
                        type_name: stringify!($name),
                        value: i64::from(v),
                        min: 0,
                        max: stepped_param_enum!(@max_prog $( $prog ),+),
                    }),
                }
            }
        }

        impl TryFrom<u8> for $name {
            type Error = Error;

            /// Converts from an exact TX value.
            fn try_from(value: u8) -> Result<Self> {
                match value {
                    $( x if x == $tx => Ok(Self::$variant), )+
                    _ => Err(Error::OutOfRange {
                        type_name: stringify!($name),
                        value: i64::from(value),
                        min: 0,
                        max: 127,
                    }),
                }
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                match self {
                    $( Self::$variant => write!(f, "{}", stepped_param_enum!(@display $variant $(, $disp)?)), )+
                }
            }
        }
    };

    // Helper: pick custom display string or stringify the variant.
    (@display $variant:ident, $disp:literal) => { $disp };
    (@display $variant:ident) => { stringify!($variant) };

    // Helper: compute max program value.
    (@max_prog $first:expr $(, $rest:expr)*) => {{
        let mut max: i64 = $first as i64;
        $( if ($rest as i64) > max { max = $rest as i64; } )*
        max
    }};
}

// ---------------------------------------------------------------------------
// 2-variant enums (TX: 0, 127 / RX: 0-63, 64-127)
// ---------------------------------------------------------------------------

stepped_param_enum! {
    /// VCO sync on/off.
    Sync {
        Off => { tx: 0, rx: 0..=63, prog: 0 },
        On  => { tx: 127, rx: 64..=127, prog: 1 },
    }
}

stepped_param_enum! {
    /// Ring modulation on/off.
    Ring {
        Off => { tx: 0, rx: 0..=63, prog: 0 },
        On  => { tx: 127, rx: 64..=127, prog: 1 },
    }
}

// ---------------------------------------------------------------------------
// 3-variant enums (TX: 0, 64, 127 / RX: 0-42, 43-85, 86-127)
// ---------------------------------------------------------------------------

stepped_param_enum! {
    /// VCO waveform selector.
    VcoWave {
        Sqr => { tx: 0, rx: 0..=42, prog: 0 },
        Tri => { tx: 64, rx: 43..=85, prog: 1 },
        Saw => { tx: 127, rx: 86..=127, prog: 2 },
    }
}

stepped_param_enum! {
    /// LFO waveform selector.
    LfoWave {
        Sqr => { tx: 0, rx: 0..=42, prog: 0 },
        Tri => { tx: 64, rx: 43..=85, prog: 1 },
        Saw => { tx: 127, rx: 86..=127, prog: 2 },
    }
}

stepped_param_enum! {
    /// LFO mode selector.
    LfoMode {
        OneShot => { tx: 0, rx: 0..=42, prog: 0 },
        Normal  => { tx: 64, rx: 43..=85, prog: 1 },
        Bpm     => { tx: 127, rx: 86..=127, prog: 2 },
    }
}

stepped_param_enum! {
    /// LFO target selector.
    LfoTarget {
        Cutoff => { tx: 0, rx: 0..=42, prog: 0 },
        Shape  => { tx: 64, rx: 43..=85, prog: 1 },
        Pitch  => { tx: 127, rx: 86..=127, prog: 2 },
    }
}

stepped_param_enum! {
    /// EG target selector.
    EgTarget {
        Cutoff => { tx: 0, rx: 0..=42, prog: 0 },
        Pitch2 => { tx: 64, rx: 43..=85, prog: 1 },
        Pitch  => { tx: 127, rx: 86..=127, prog: 2 },
    }
}

stepped_param_enum! {
    /// Multi-engine oscillator type.
    MultiType {
        Noise => { tx: 0, rx: 0..=42, prog: 0 },
        Vpm   => { tx: 64, rx: 43..=85, prog: 1 },
        User  => { tx: 127, rx: 86..=127, prog: 2 },
    }
}

stepped_param_enum! {
    /// Cutoff key-tracking amount.
    CutoffKeytrack {
        Off  => { tx: 0, rx: 0..=42, prog: 0, display: "0%" },
        Half => { tx: 64, rx: 43..=85, prog: 1, display: "50%" },
        Full => { tx: 127, rx: 86..=127, prog: 2, display: "100%" },
    }
}

stepped_param_enum! {
    /// Cutoff drive amount.
    CutoffDrive {
        Off  => { tx: 0, rx: 0..=42, prog: 0, display: "0%" },
        Half => { tx: 64, rx: 43..=85, prog: 1, display: "50%" },
        Full => { tx: 127, rx: 86..=127, prog: 2, display: "100%" },
    }
}

stepped_param_enum! {
    /// Mod-FX sub-type for Ensemble.
    ModFxSubTypeEnsemble {
        Stereo => { tx: 0, rx: 0..=42, prog: 0 },
        Light  => { tx: 64, rx: 43..=85, prog: 1 },
        Mono   => { tx: 127, rx: 86..=127, prog: 2 },
    }
}

// ---------------------------------------------------------------------------
// 4-variant enums (TX: 0, 42, 84, 127 / RX: 0-31, 32-63, 64-95, 96-127)
// ---------------------------------------------------------------------------

stepped_param_enum! {
    /// VCO octave selector.
    VcoOctave {
        Sixteen => { tx: 0, rx: 0..=31, prog: 0, display: "16'" },
        Eight   => { tx: 42, rx: 32..=63, prog: 1, display: "8'" },
        Four    => { tx: 84, rx: 64..=95, prog: 2, display: "4'" },
        Two     => { tx: 127, rx: 96..=127, prog: 3, display: "2'" },
    }
}

stepped_param_enum! {
    /// Multi-engine noise type selector.
    MultiSelectNoise {
        High  => { tx: 0, rx: 0..=31, prog: 0 },
        Low   => { tx: 42, rx: 32..=63, prog: 1 },
        Peak  => { tx: 84, rx: 64..=95, prog: 2 },
        Decim => { tx: 127, rx: 96..=127, prog: 3 },
    }
}

// ---------------------------------------------------------------------------
// 5-variant enums (irregular TX)
// ---------------------------------------------------------------------------

stepped_param_enum! {
    /// Mod-FX type selector.
    ModFxType {
        Chorus   => { tx: 0, rx: 0..=25, prog: 0 },
        Ensemble => { tx: 38, rx: 26..=51, prog: 1 },
        Phaser   => { tx: 64, rx: 52..=76, prog: 2 },
        Flanger  => { tx: 84, rx: 77..=102, prog: 3 },
        User     => { tx: 127, rx: 103..=127, prog: 4 },
    }
}

stepped_param_enum! {
    /// Voice mode type selector.
    VoiceModeType {
        Poly     => { tx: 0, rx: 0..=25, prog: 0 },
        Unison   => { tx: 32, rx: 26..=51, prog: 1 },
        Chord    => { tx: 64, rx: 52..=76, prog: 2 },
        Arp      => { tx: 96, rx: 77..=102, prog: 3 },
        ArpLatch => { tx: 127, rx: 103..=127, prog: 4 },
    }
}

// ---------------------------------------------------------------------------
// 8-variant enums (TX: 0,16,32,48,64,80,96,127)
// RX bands: 0-15, 16-31, 32-47, 48-63, 64-79, 80-95, 96-111, 112-127
// ---------------------------------------------------------------------------

stepped_param_enum! {
    /// Mod-FX sub-type for Chorus.
    ModFxSubTypeChorus {
        Stereo    => { tx: 0, rx: 0..=15, prog: 0 },
        Light     => { tx: 16, rx: 16..=31, prog: 1 },
        Deep      => { tx: 32, rx: 32..=47, prog: 2 },
        Triphase  => { tx: 48, rx: 48..=63, prog: 3 },
        Harmonic  => { tx: 64, rx: 64..=79, prog: 4 },
        Mono      => { tx: 80, rx: 80..=95, prog: 5 },
        Feedback  => { tx: 96, rx: 96..=111, prog: 6 },
        Vibrato   => { tx: 127, rx: 112..=127, prog: 7 },
    }
}

stepped_param_enum! {
    /// Mod-FX sub-type for Phaser.
    ModFxSubTypePhaser {
        Stereo    => { tx: 0, rx: 0..=15, prog: 0 },
        Fast      => { tx: 16, rx: 16..=31, prog: 1 },
        Orange    => { tx: 32, rx: 32..=47, prog: 2 },
        Small     => { tx: 48, rx: 48..=63, prog: 3 },
        SmallReso => { tx: 64, rx: 64..=79, prog: 4 },
        Black     => { tx: 80, rx: 80..=95, prog: 5 },
        Formant   => { tx: 96, rx: 96..=111, prog: 6 },
        Twinkle   => { tx: 127, rx: 112..=127, prog: 7 },
    }
}

stepped_param_enum! {
    /// Mod-FX sub-type for Flanger.
    ModFxSubTypeFlanger {
        Stereo    => { tx: 0, rx: 0..=15, prog: 0 },
        Light     => { tx: 16, rx: 16..=31, prog: 1 },
        Mono      => { tx: 32, rx: 32..=47, prog: 2 },
        HighSweep => { tx: 48, rx: 48..=63, prog: 3 },
        MidSweep  => { tx: 64, rx: 64..=79, prog: 4 },
        PanSweep  => { tx: 80, rx: 80..=95, prog: 5 },
        MonoSweep => { tx: 96, rx: 96..=111, prog: 6 },
        Triphase  => { tx: 127, rx: 112..=127, prog: 7 },
    }
}

// ---------------------------------------------------------------------------
// 16-variant enums (TX: 0,8,16,24,32,40,48,56,64,72,80,88,96,104,112,127)
// RX bands: 0-7, 8-15, 16-23, 24-31, 32-39, 40-47, 48-55, 56-63,
//           64-71, 72-79, 80-87, 88-95, 96-103, 104-111, 112-119, 120-127
// ---------------------------------------------------------------------------

stepped_param_enum! {
    /// Multi-engine VPM oscillator type selector.
    MultiSelectVpm {
        Sin1   => { tx: 0, rx: 0..=7, prog: 0 },
        Sin2   => { tx: 8, rx: 8..=15, prog: 1 },
        Sin3   => { tx: 16, rx: 16..=23, prog: 2 },
        Sin4   => { tx: 24, rx: 24..=31, prog: 3 },
        Saw1   => { tx: 32, rx: 32..=39, prog: 4 },
        Saw2   => { tx: 40, rx: 40..=47, prog: 5 },
        Squ1   => { tx: 48, rx: 48..=55, prog: 6 },
        Squ2   => { tx: 56, rx: 56..=63, prog: 7 },
        Fat1   => { tx: 64, rx: 64..=71, prog: 8 },
        Fat2   => { tx: 72, rx: 72..=79, prog: 9 },
        Air1   => { tx: 80, rx: 80..=87, prog: 10 },
        Air2   => { tx: 88, rx: 88..=95, prog: 11 },
        Decay1 => { tx: 96, rx: 96..=103, prog: 12 },
        Decay2 => { tx: 104, rx: 104..=111, prog: 13 },
        Creep  => { tx: 112, rx: 112..=119, prog: 14 },
        Throat => { tx: 127, rx: 120..=127, prog: 15 },
    }
}

stepped_param_enum! {
    /// Multi-engine user oscillator slot selector.
    MultiSelectUser {
        User1  => { tx: 0, rx: 0..=7, prog: 0 },
        User2  => { tx: 8, rx: 8..=15, prog: 1 },
        User3  => { tx: 16, rx: 16..=23, prog: 2 },
        User4  => { tx: 24, rx: 24..=31, prog: 3 },
        User5  => { tx: 32, rx: 32..=39, prog: 4 },
        User6  => { tx: 40, rx: 40..=47, prog: 5 },
        User7  => { tx: 48, rx: 48..=55, prog: 6 },
        User8  => { tx: 56, rx: 56..=63, prog: 7 },
        User9  => { tx: 64, rx: 64..=71, prog: 8 },
        User10 => { tx: 72, rx: 72..=79, prog: 9 },
        User11 => { tx: 80, rx: 80..=87, prog: 10 },
        User12 => { tx: 88, rx: 88..=95, prog: 11 },
        User13 => { tx: 96, rx: 96..=103, prog: 12 },
        User14 => { tx: 104, rx: 104..=111, prog: 13 },
        User15 => { tx: 112, rx: 112..=119, prog: 14 },
        User16 => { tx: 127, rx: 120..=127, prog: 15 },
    }
}

stepped_param_enum! {
    /// Mod-FX sub-type for User effects.
    ModFxSubTypeUser {
        User1  => { tx: 0, rx: 0..=7, prog: 0 },
        User2  => { tx: 8, rx: 8..=15, prog: 1 },
        User3  => { tx: 16, rx: 16..=23, prog: 2 },
        User4  => { tx: 24, rx: 24..=31, prog: 3 },
        User5  => { tx: 32, rx: 32..=39, prog: 4 },
        User6  => { tx: 40, rx: 40..=47, prog: 5 },
        User7  => { tx: 48, rx: 48..=55, prog: 6 },
        User8  => { tx: 56, rx: 56..=63, prog: 7 },
        User9  => { tx: 64, rx: 64..=71, prog: 8 },
        User10 => { tx: 72, rx: 72..=79, prog: 9 },
        User11 => { tx: 80, rx: 80..=87, prog: 10 },
        User12 => { tx: 88, rx: 88..=95, prog: 11 },
        User13 => { tx: 96, rx: 96..=103, prog: 12 },
        User14 => { tx: 104, rx: 104..=111, prog: 13 },
        User15 => { tx: 112, rx: 112..=119, prog: 14 },
        User16 => { tx: 127, rx: 120..=127, prog: 15 },
    }
}

// ---------------------------------------------------------------------------
// 20-variant enum — DelaySubType (irregular TX/RX)
// ---------------------------------------------------------------------------

stepped_param_enum! {
    /// Delay effect sub-type selector.
    DelaySubType {
        Stereo    => { tx: 0, rx: 0..=6, prog: 0 },
        Mono      => { tx: 7, rx: 7..=12, prog: 1 },
        PingPong  => { tx: 13, rx: 13..=19, prog: 2 },
        Hipass    => { tx: 20, rx: 20..=25, prog: 3 },
        Tape      => { tx: 26, rx: 26..=31, prog: 4 },
        OneTap    => { tx: 32, rx: 32..=38, prog: 5 },
        StereoBpm => { tx: 39, rx: 39..=44, prog: 6 },
        MonoBpm   => { tx: 45, rx: 45..=51, prog: 7 },
        PingBpm   => { tx: 52, rx: 52..=57, prog: 8 },
        HipassBpm => { tx: 58, rx: 58..=63, prog: 9 },
        TapeBpm   => { tx: 64, rx: 64..=70, prog: 10 },
        Doubling  => { tx: 71, rx: 71..=76, prog: 11 },
        User1     => { tx: 77, rx: 77..=83, prog: 12 },
        User2     => { tx: 84, rx: 84..=89, prog: 13 },
        User3     => { tx: 90, rx: 90..=95, prog: 14 },
        User4     => { tx: 96, rx: 96..=102, prog: 15 },
        User5     => { tx: 103, rx: 103..=108, prog: 16 },
        User6     => { tx: 109, rx: 109..=115, prog: 17 },
        User7     => { tx: 116, rx: 116..=121, prog: 18 },
        User8     => { tx: 127, rx: 122..=127, prog: 19 },
    }
}

// ---------------------------------------------------------------------------
// 18-variant enum — ReverbSubType (irregular TX/RX)
// ---------------------------------------------------------------------------

stepped_param_enum! {
    /// Reverb effect sub-type selector.
    ReverbSubType {
        Hall     => { tx: 0, rx: 0..=7, prog: 0 },
        Smooth   => { tx: 8, rx: 8..=14, prog: 1 },
        Arena    => { tx: 15, rx: 15..=21, prog: 2 },
        Plate    => { tx: 22, rx: 22..=28, prog: 3 },
        Room     => { tx: 29, rx: 29..=35, prog: 4 },
        EarlyRef => { tx: 36, rx: 36..=42, prog: 5 },
        Space    => { tx: 43, rx: 43..=49, prog: 6 },
        Riser    => { tx: 50, rx: 50..=56, prog: 7 },
        Submarine => { tx: 57, rx: 57..=63, prog: 8 },
        Horror   => { tx: 64, rx: 64..=71, prog: 9 },
        User1    => { tx: 72, rx: 72..=78, prog: 10 },
        User2    => { tx: 79, rx: 79..=85, prog: 11 },
        User3    => { tx: 86, rx: 86..=92, prog: 12 },
        User4    => { tx: 93, rx: 93..=99, prog: 13 },
        User5    => { tx: 100, rx: 100..=106, prog: 14 },
        User6    => { tx: 107, rx: 107..=113, prog: 15 },
        User7    => { tx: 117, rx: 114..=120, prog: 16 },
        User8    => { tx: 127, rx: 121..=127, prog: 17 },
    }
}

// ---------------------------------------------------------------------------
// NRPN-only small enums (program values as TX/RX)
// ---------------------------------------------------------------------------

stepped_param_enum! {
    /// CV input mode selector.
    CvInMode {
        Modulation  => { tx: 0, rx: 0..=0, prog: 0 },
        CvGatePlus  => { tx: 1, rx: 1..=1, prog: 1 },
        CvGateMinus => { tx: 2, rx: 2..=2, prog: 2 },
    }
}

stepped_param_enum! {
    /// User parameter display type.
    UserParamType {
        Percent => { tx: 0, rx: 0..=0, prog: 0 },
        Bipolar => { tx: 1, rx: 1..=1, prog: 1 },
        Select  => { tx: 2, rx: 2..=2, prog: 2 },
    }
}

stepped_param_enum! {
    /// Multi-engine audio routing.
    MultiRouting {
        PreVcf  => { tx: 0, rx: 0..=0, prog: 0 },
        PostVcf => { tx: 1, rx: 1..=1, prog: 1 },
    }
}

stepped_param_enum! {
    /// Portamento mode.
    PortamentoMode {
        Auto => { tx: 0, rx: 0..=0, prog: 0 },
        On   => { tx: 1, rx: 1..=1, prog: 1 },
    }
}

stepped_param_enum! {
    /// LFO target oscillator selector.
    LfoTargetOsc {
        All      => { tx: 0, rx: 0..=0, prog: 0 },
        Vco1Vco2 => { tx: 1, rx: 1..=1, prog: 1 },
        Vco2     => { tx: 2, rx: 2..=2, prog: 2 },
        Multi    => { tx: 3, rx: 3..=3, prog: 3 },
    }
}

// ---------------------------------------------------------------------------
// 29-variant — ModAssignTarget (program values 0-28)
// ---------------------------------------------------------------------------

stepped_param_enum! {
    /// Modulation assignment target (joystick, CV, aftertouch).
    ModAssignTarget {
        None           => { tx: 0, rx: 0..=0, prog: 0 },
        GateTime       => { tx: 1, rx: 1..=1, prog: 1 },
        PitchBend      => { tx: 2, rx: 2..=2, prog: 2 },
        CutoffVelocity => { tx: 3, rx: 3..=3, prog: 3 },
        AmpVelocity    => { tx: 4, rx: 4..=4, prog: 4 },
        MultiCtrl1     => { tx: 5, rx: 5..=5, prog: 5 },
        MultiCtrl2     => { tx: 6, rx: 6..=6, prog: 6 },
        MultiCtrl3     => { tx: 7, rx: 7..=7, prog: 7 },
        MultiCtrl4     => { tx: 8, rx: 8..=8, prog: 8 },
        Vco1Pitch      => { tx: 9, rx: 9..=9, prog: 9 },
        Vco1Shape      => { tx: 10, rx: 10..=10, prog: 10 },
        Vco2Pitch      => { tx: 11, rx: 11..=11, prog: 11 },
        Vco2Shape      => { tx: 12, rx: 12..=12, prog: 12 },
        CrossModDepth  => { tx: 13, rx: 13..=13, prog: 13 },
        MultiShape     => { tx: 14, rx: 14..=14, prog: 14 },
        MultiShiftShape => { tx: 15, rx: 15..=15, prog: 15 },
        Cutoff         => { tx: 16, rx: 16..=16, prog: 16 },
        Resonance      => { tx: 17, rx: 17..=17, prog: 17 },
        AmpLevel       => { tx: 18, rx: 18..=18, prog: 18 },
        AmpPan         => { tx: 19, rx: 19..=19, prog: 19 },
        EgAttack       => { tx: 20, rx: 20..=20, prog: 20 },
        EgDecay        => { tx: 21, rx: 21..=21, prog: 21 },
        EgSustain      => { tx: 22, rx: 22..=22, prog: 22 },
        EgRelease      => { tx: 23, rx: 23..=23, prog: 23 },
        LfoRate        => { tx: 24, rx: 24..=24, prog: 24 },
        LfoInt         => { tx: 25, rx: 25..=25, prog: 25 },
        DelayDryWet    => { tx: 26, rx: 26..=26, prog: 26 },
        ReverbDryWet   => { tx: 27, rx: 27..=27, prog: 27 },
        PortamentoTime => { tx: 28, rx: 28..=28, prog: 28 },
    }
}

// ---------------------------------------------------------------------------
// 39-variant — MicroTuning (program values 0-38)
// ---------------------------------------------------------------------------

stepped_param_enum! {
    /// Micro-tuning scale selection.
    MicroTuning {
        EqualTemp          => { tx: 0, rx: 0..=0, prog: 0 },
        PureMajor          => { tx: 1, rx: 1..=1, prog: 1 },
        PureMinor          => { tx: 2, rx: 2..=2, prog: 2 },
        Pythagorean        => { tx: 3, rx: 3..=3, prog: 3 },
        Werkmeister        => { tx: 4, rx: 4..=4, prog: 4 },
        Kirnberger         => { tx: 5, rx: 5..=5, prog: 5 },
        Slendro            => { tx: 6, rx: 6..=6, prog: 6 },
        Pelog              => { tx: 7, rx: 7..=7, prog: 7 },
        Ionian             => { tx: 8, rx: 8..=8, prog: 8 },
        Dorian             => { tx: 9, rx: 9..=9, prog: 9 },
        Aeolian            => { tx: 10, rx: 10..=10, prog: 10 },
        MajorBlues         => { tx: 11, rx: 11..=11, prog: 11 },
        MinorBlues         => { tx: 12, rx: 12..=12, prog: 12 },
        Diminished         => { tx: 13, rx: 13..=13, prog: 13 },
        CombiDiminished    => { tx: 14, rx: 14..=14, prog: 14 },
        MajorPentatonic    => { tx: 15, rx: 15..=15, prog: 15 },
        MinorPentatonic    => { tx: 16, rx: 16..=16, prog: 16 },
        RagaChalanata      => { tx: 17, rx: 17..=17, prog: 17 },
        RagaGamanashrama   => { tx: 18, rx: 18..=18, prog: 18 },
        RagaTodi           => { tx: 19, rx: 19..=19, prog: 19 },
        RagaShruti         => { tx: 20, rx: 20..=20, prog: 20 },
        UserScale1         => { tx: 21, rx: 21..=21, prog: 21 },
        UserScale2         => { tx: 22, rx: 22..=22, prog: 22 },
        UserScale3         => { tx: 23, rx: 23..=23, prog: 23 },
        UserScale4         => { tx: 24, rx: 24..=24, prog: 24 },
        UserScale5         => { tx: 25, rx: 25..=25, prog: 25 },
        UserScale6         => { tx: 26, rx: 26..=26, prog: 26 },
        UserOctave1        => { tx: 27, rx: 27..=27, prog: 27 },
        UserOctave2        => { tx: 28, rx: 28..=28, prog: 28 },
        UserOctave3        => { tx: 29, rx: 29..=29, prog: 29 },
        UserOctave4        => { tx: 30, rx: 30..=30, prog: 30 },
        UserOctave5        => { tx: 31, rx: 31..=31, prog: 31 },
        UserOctave6        => { tx: 32, rx: 32..=32, prog: 32 },
        Reverse1           => { tx: 33, rx: 33..=33, prog: 33 },
        Reverse2           => { tx: 34, rx: 34..=34, prog: 34 },
        AFX001             => { tx: 35, rx: 35..=35, prog: 35 },
        AFX002             => { tx: 36, rx: 36..=36, prog: 36 },
        AFX003             => { tx: 37, rx: 37..=37, prog: 37 },
        AFX004             => { tx: 38, rx: 38..=38, prog: 38 },
    }
}

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

/// Asserts that [`SteppedParam::from_rx_value`] covers all 128 MIDI values
/// without error for a type whose RX bands tile 0..=127.
#[cfg(test)]
pub(crate) fn assert_rx_full_coverage<T: SteppedParam + std::fmt::Debug>() {
    for v in 0..=127u8 {
        T::from_rx_value(v).unwrap_or_else(|e| panic!("from_rx_value({v}) failed: {e}"));
    }
}

/// Asserts TX round-trip: `from_rx_value(to_tx_value(variant))` recovers the
/// original variant.
#[cfg(test)]
pub(crate) fn assert_tx_roundtrip<T: SteppedParam + std::fmt::Debug + PartialEq>(variants: &[T]) {
    for &v in variants {
        let tx = v.to_tx_value();
        let recovered = T::from_rx_value(tx)
            .unwrap_or_else(|e| panic!("from_rx_value(tx={tx}) for {v:?} failed: {e}"));
        assert_eq!(recovered, v, "TX round-trip failed for {v:?} (tx={tx})");
    }
}

/// Asserts program round-trip: `from_program_value(to_program_value(variant))`
/// recovers the original variant.
#[cfg(test)]
pub(crate) fn assert_program_roundtrip<T: SteppedParam + std::fmt::Debug + PartialEq>(
    variants: &[T],
) {
    for &v in variants {
        let p = v.to_program_value();
        let recovered = T::from_program_value(p)
            .unwrap_or_else(|e| panic!("from_program_value({p}) for {v:?} failed: {e}"));
        assert_eq!(
            recovered, v,
            "Program round-trip failed for {v:?} (prog={p})"
        );
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // Convenience macro to reduce boilerplate per enum.
    macro_rules! test_stepped_enum {
        ($name:ident, $type:ty, [ $( $variant:expr ),+ $(,)? ]) => {
            mod $name {
                use super::*;

                const ALL: &[$type] = &[ $( $variant ),+ ];

                #[test]
                fn tx_roundtrip() {
                    assert_tx_roundtrip(ALL);
                }

                #[test]
                fn rx_full_coverage() {
                    assert_rx_full_coverage::<$type>();
                }

                #[test]
                fn program_roundtrip() {
                    assert_program_roundtrip(ALL);
                }

                #[test]
                fn display_not_empty() {
                    for v in ALL {
                        let s = format!("{v}");
                        assert!(!s.is_empty(), "Display for {v:?} is empty");
                    }
                }

                #[test]
                fn try_from_invalid() {
                    // 200 is never a valid TX value
                    assert!(<$type>::try_from(200u8).is_err());
                }

                #[test]
                fn from_program_invalid() {
                    assert!(<$type>::from_program_value(255).is_err());
                }
            }
        };
    }

    // --- 2-variant ---

    test_stepped_enum!(sync, Sync, [Sync::Off, Sync::On]);
    test_stepped_enum!(ring, Ring, [Ring::Off, Ring::On]);

    // --- 3-variant ---

    test_stepped_enum!(
        vco_wave,
        VcoWave,
        [VcoWave::Sqr, VcoWave::Tri, VcoWave::Saw]
    );
    test_stepped_enum!(
        lfo_wave,
        LfoWave,
        [LfoWave::Sqr, LfoWave::Tri, LfoWave::Saw]
    );
    test_stepped_enum!(
        lfo_mode,
        LfoMode,
        [LfoMode::OneShot, LfoMode::Normal, LfoMode::Bpm]
    );
    test_stepped_enum!(
        lfo_target,
        LfoTarget,
        [LfoTarget::Cutoff, LfoTarget::Shape, LfoTarget::Pitch]
    );
    test_stepped_enum!(
        eg_target,
        EgTarget,
        [EgTarget::Cutoff, EgTarget::Pitch2, EgTarget::Pitch]
    );
    test_stepped_enum!(
        multi_type,
        MultiType,
        [MultiType::Noise, MultiType::Vpm, MultiType::User]
    );
    test_stepped_enum!(
        cutoff_keytrack,
        CutoffKeytrack,
        [
            CutoffKeytrack::Off,
            CutoffKeytrack::Half,
            CutoffKeytrack::Full
        ]
    );
    test_stepped_enum!(
        cutoff_drive,
        CutoffDrive,
        [CutoffDrive::Off, CutoffDrive::Half, CutoffDrive::Full]
    );
    test_stepped_enum!(
        mod_fx_sub_type_ensemble,
        ModFxSubTypeEnsemble,
        [
            ModFxSubTypeEnsemble::Stereo,
            ModFxSubTypeEnsemble::Light,
            ModFxSubTypeEnsemble::Mono
        ]
    );

    // --- 4-variant ---

    test_stepped_enum!(
        vco_octave,
        VcoOctave,
        [
            VcoOctave::Sixteen,
            VcoOctave::Eight,
            VcoOctave::Four,
            VcoOctave::Two
        ]
    );
    test_stepped_enum!(
        multi_select_noise,
        MultiSelectNoise,
        [
            MultiSelectNoise::High,
            MultiSelectNoise::Low,
            MultiSelectNoise::Peak,
            MultiSelectNoise::Decim
        ]
    );

    // --- 5-variant ---

    test_stepped_enum!(
        mod_fx_type,
        ModFxType,
        [
            ModFxType::Chorus,
            ModFxType::Ensemble,
            ModFxType::Phaser,
            ModFxType::Flanger,
            ModFxType::User
        ]
    );
    test_stepped_enum!(
        voice_mode_type,
        VoiceModeType,
        [
            VoiceModeType::Poly,
            VoiceModeType::Unison,
            VoiceModeType::Chord,
            VoiceModeType::Arp,
            VoiceModeType::ArpLatch
        ]
    );

    // --- 8-variant ---

    test_stepped_enum!(
        mod_fx_sub_type_chorus,
        ModFxSubTypeChorus,
        [
            ModFxSubTypeChorus::Stereo,
            ModFxSubTypeChorus::Light,
            ModFxSubTypeChorus::Deep,
            ModFxSubTypeChorus::Triphase,
            ModFxSubTypeChorus::Harmonic,
            ModFxSubTypeChorus::Mono,
            ModFxSubTypeChorus::Feedback,
            ModFxSubTypeChorus::Vibrato
        ]
    );
    test_stepped_enum!(
        mod_fx_sub_type_phaser,
        ModFxSubTypePhaser,
        [
            ModFxSubTypePhaser::Stereo,
            ModFxSubTypePhaser::Fast,
            ModFxSubTypePhaser::Orange,
            ModFxSubTypePhaser::Small,
            ModFxSubTypePhaser::SmallReso,
            ModFxSubTypePhaser::Black,
            ModFxSubTypePhaser::Formant,
            ModFxSubTypePhaser::Twinkle
        ]
    );
    test_stepped_enum!(
        mod_fx_sub_type_flanger,
        ModFxSubTypeFlanger,
        [
            ModFxSubTypeFlanger::Stereo,
            ModFxSubTypeFlanger::Light,
            ModFxSubTypeFlanger::Mono,
            ModFxSubTypeFlanger::HighSweep,
            ModFxSubTypeFlanger::MidSweep,
            ModFxSubTypeFlanger::PanSweep,
            ModFxSubTypeFlanger::MonoSweep,
            ModFxSubTypeFlanger::Triphase
        ]
    );

    // --- 16-variant ---

    test_stepped_enum!(
        multi_select_vpm,
        MultiSelectVpm,
        [
            MultiSelectVpm::Sin1,
            MultiSelectVpm::Sin2,
            MultiSelectVpm::Sin3,
            MultiSelectVpm::Sin4,
            MultiSelectVpm::Saw1,
            MultiSelectVpm::Saw2,
            MultiSelectVpm::Squ1,
            MultiSelectVpm::Squ2,
            MultiSelectVpm::Fat1,
            MultiSelectVpm::Fat2,
            MultiSelectVpm::Air1,
            MultiSelectVpm::Air2,
            MultiSelectVpm::Decay1,
            MultiSelectVpm::Decay2,
            MultiSelectVpm::Creep,
            MultiSelectVpm::Throat
        ]
    );
    test_stepped_enum!(
        multi_select_user,
        MultiSelectUser,
        [
            MultiSelectUser::User1,
            MultiSelectUser::User2,
            MultiSelectUser::User3,
            MultiSelectUser::User4,
            MultiSelectUser::User5,
            MultiSelectUser::User6,
            MultiSelectUser::User7,
            MultiSelectUser::User8,
            MultiSelectUser::User9,
            MultiSelectUser::User10,
            MultiSelectUser::User11,
            MultiSelectUser::User12,
            MultiSelectUser::User13,
            MultiSelectUser::User14,
            MultiSelectUser::User15,
            MultiSelectUser::User16
        ]
    );
    test_stepped_enum!(
        mod_fx_sub_type_user,
        ModFxSubTypeUser,
        [
            ModFxSubTypeUser::User1,
            ModFxSubTypeUser::User2,
            ModFxSubTypeUser::User3,
            ModFxSubTypeUser::User4,
            ModFxSubTypeUser::User5,
            ModFxSubTypeUser::User6,
            ModFxSubTypeUser::User7,
            ModFxSubTypeUser::User8,
            ModFxSubTypeUser::User9,
            ModFxSubTypeUser::User10,
            ModFxSubTypeUser::User11,
            ModFxSubTypeUser::User12,
            ModFxSubTypeUser::User13,
            ModFxSubTypeUser::User14,
            ModFxSubTypeUser::User15,
            ModFxSubTypeUser::User16
        ]
    );

    // --- 20-variant (Delay) ---

    test_stepped_enum!(
        delay_sub_type,
        DelaySubType,
        [
            DelaySubType::Stereo,
            DelaySubType::Mono,
            DelaySubType::PingPong,
            DelaySubType::Hipass,
            DelaySubType::Tape,
            DelaySubType::OneTap,
            DelaySubType::StereoBpm,
            DelaySubType::MonoBpm,
            DelaySubType::PingBpm,
            DelaySubType::HipassBpm,
            DelaySubType::TapeBpm,
            DelaySubType::Doubling,
            DelaySubType::User1,
            DelaySubType::User2,
            DelaySubType::User3,
            DelaySubType::User4,
            DelaySubType::User5,
            DelaySubType::User6,
            DelaySubType::User7,
            DelaySubType::User8
        ]
    );

    // --- 18-variant (Reverb) ---

    test_stepped_enum!(
        reverb_sub_type,
        ReverbSubType,
        [
            ReverbSubType::Hall,
            ReverbSubType::Smooth,
            ReverbSubType::Arena,
            ReverbSubType::Plate,
            ReverbSubType::Room,
            ReverbSubType::EarlyRef,
            ReverbSubType::Space,
            ReverbSubType::Riser,
            ReverbSubType::Submarine,
            ReverbSubType::Horror,
            ReverbSubType::User1,
            ReverbSubType::User2,
            ReverbSubType::User3,
            ReverbSubType::User4,
            ReverbSubType::User5,
            ReverbSubType::User6,
            ReverbSubType::User7,
            ReverbSubType::User8
        ]
    );

    // --- NRPN-only small enums ---

    // CvInMode, UserParamType, MultiRouting, PortamentoMode, LfoTargetOsc
    // have point-valued RX bands, so rx_full_coverage won't cover 0..=127.
    // We test them individually.

    mod cv_in_mode {
        use super::*;

        #[test]
        fn tx_roundtrip() {
            assert_tx_roundtrip(&[
                CvInMode::Modulation,
                CvInMode::CvGatePlus,
                CvInMode::CvGateMinus,
            ]);
        }

        #[test]
        fn program_roundtrip() {
            assert_program_roundtrip(&[
                CvInMode::Modulation,
                CvInMode::CvGatePlus,
                CvInMode::CvGateMinus,
            ]);
        }

        #[test]
        fn rx_out_of_band() {
            assert!(CvInMode::from_rx_value(3).is_err());
            assert!(CvInMode::from_rx_value(127).is_err());
        }

        #[test]
        fn display() {
            assert_eq!(format!("{}", CvInMode::CvGatePlus), "CvGatePlus");
        }
    }

    mod user_param_type {
        use super::*;

        #[test]
        fn tx_roundtrip() {
            assert_tx_roundtrip(&[
                UserParamType::Percent,
                UserParamType::Bipolar,
                UserParamType::Select,
            ]);
        }

        #[test]
        fn program_roundtrip() {
            assert_program_roundtrip(&[
                UserParamType::Percent,
                UserParamType::Bipolar,
                UserParamType::Select,
            ]);
        }

        #[test]
        fn rx_out_of_band() {
            assert!(UserParamType::from_rx_value(3).is_err());
        }
    }

    mod multi_routing {
        use super::*;

        #[test]
        fn tx_roundtrip() {
            assert_tx_roundtrip(&[MultiRouting::PreVcf, MultiRouting::PostVcf]);
        }

        #[test]
        fn program_roundtrip() {
            assert_program_roundtrip(&[MultiRouting::PreVcf, MultiRouting::PostVcf]);
        }

        #[test]
        fn rx_out_of_band() {
            assert!(MultiRouting::from_rx_value(2).is_err());
        }
    }

    mod portamento_mode {
        use super::*;

        #[test]
        fn tx_roundtrip() {
            assert_tx_roundtrip(&[PortamentoMode::Auto, PortamentoMode::On]);
        }

        #[test]
        fn program_roundtrip() {
            assert_program_roundtrip(&[PortamentoMode::Auto, PortamentoMode::On]);
        }

        #[test]
        fn rx_out_of_band() {
            assert!(PortamentoMode::from_rx_value(2).is_err());
        }
    }

    mod lfo_target_osc {
        use super::*;

        #[test]
        fn tx_roundtrip() {
            assert_tx_roundtrip(&[
                LfoTargetOsc::All,
                LfoTargetOsc::Vco1Vco2,
                LfoTargetOsc::Vco2,
                LfoTargetOsc::Multi,
            ]);
        }

        #[test]
        fn program_roundtrip() {
            assert_program_roundtrip(&[
                LfoTargetOsc::All,
                LfoTargetOsc::Vco1Vco2,
                LfoTargetOsc::Vco2,
                LfoTargetOsc::Multi,
            ]);
        }

        #[test]
        fn rx_out_of_band() {
            assert!(LfoTargetOsc::from_rx_value(4).is_err());
        }
    }

    // --- ModAssignTarget ---

    mod mod_assign_target {
        use super::*;

        const ALL: &[ModAssignTarget] = &[
            ModAssignTarget::None,
            ModAssignTarget::GateTime,
            ModAssignTarget::PitchBend,
            ModAssignTarget::CutoffVelocity,
            ModAssignTarget::AmpVelocity,
            ModAssignTarget::MultiCtrl1,
            ModAssignTarget::MultiCtrl2,
            ModAssignTarget::MultiCtrl3,
            ModAssignTarget::MultiCtrl4,
            ModAssignTarget::Vco1Pitch,
            ModAssignTarget::Vco1Shape,
            ModAssignTarget::Vco2Pitch,
            ModAssignTarget::Vco2Shape,
            ModAssignTarget::CrossModDepth,
            ModAssignTarget::MultiShape,
            ModAssignTarget::MultiShiftShape,
            ModAssignTarget::Cutoff,
            ModAssignTarget::Resonance,
            ModAssignTarget::AmpLevel,
            ModAssignTarget::AmpPan,
            ModAssignTarget::EgAttack,
            ModAssignTarget::EgDecay,
            ModAssignTarget::EgSustain,
            ModAssignTarget::EgRelease,
            ModAssignTarget::LfoRate,
            ModAssignTarget::LfoInt,
            ModAssignTarget::DelayDryWet,
            ModAssignTarget::ReverbDryWet,
            ModAssignTarget::PortamentoTime,
        ];

        #[test]
        fn tx_roundtrip() {
            assert_tx_roundtrip(ALL);
        }

        #[test]
        fn program_roundtrip() {
            assert_program_roundtrip(ALL);
        }

        #[test]
        fn rx_out_of_band() {
            assert!(ModAssignTarget::from_rx_value(29).is_err());
            assert!(ModAssignTarget::from_rx_value(127).is_err());
        }

        #[test]
        fn variant_count() {
            assert_eq!(ALL.len(), 29);
        }

        #[test]
        fn display() {
            assert_eq!(format!("{}", ModAssignTarget::None), "None");
            assert_eq!(
                format!("{}", ModAssignTarget::PortamentoTime),
                "PortamentoTime"
            );
        }
    }

    // --- MicroTuning ---

    mod micro_tuning {
        use super::*;

        const ALL: &[MicroTuning] = &[
            MicroTuning::EqualTemp,
            MicroTuning::PureMajor,
            MicroTuning::PureMinor,
            MicroTuning::Pythagorean,
            MicroTuning::Werkmeister,
            MicroTuning::Kirnberger,
            MicroTuning::Slendro,
            MicroTuning::Pelog,
            MicroTuning::Ionian,
            MicroTuning::Dorian,
            MicroTuning::Aeolian,
            MicroTuning::MajorBlues,
            MicroTuning::MinorBlues,
            MicroTuning::Diminished,
            MicroTuning::CombiDiminished,
            MicroTuning::MajorPentatonic,
            MicroTuning::MinorPentatonic,
            MicroTuning::RagaChalanata,
            MicroTuning::RagaGamanashrama,
            MicroTuning::RagaTodi,
            MicroTuning::RagaShruti,
            MicroTuning::UserScale1,
            MicroTuning::UserScale2,
            MicroTuning::UserScale3,
            MicroTuning::UserScale4,
            MicroTuning::UserScale5,
            MicroTuning::UserScale6,
            MicroTuning::UserOctave1,
            MicroTuning::UserOctave2,
            MicroTuning::UserOctave3,
            MicroTuning::UserOctave4,
            MicroTuning::UserOctave5,
            MicroTuning::UserOctave6,
            MicroTuning::Reverse1,
            MicroTuning::Reverse2,
            MicroTuning::AFX001,
            MicroTuning::AFX002,
            MicroTuning::AFX003,
            MicroTuning::AFX004,
        ];

        #[test]
        fn tx_roundtrip() {
            assert_tx_roundtrip(ALL);
        }

        #[test]
        fn program_roundtrip() {
            assert_program_roundtrip(ALL);
        }

        #[test]
        fn rx_out_of_band() {
            assert!(MicroTuning::from_rx_value(39).is_err());
            assert!(MicroTuning::from_rx_value(127).is_err());
        }

        #[test]
        fn variant_count() {
            assert_eq!(ALL.len(), 39);
        }
    }

    // --- Custom display tests ---

    #[test]
    fn cutoff_keytrack_display() {
        assert_eq!(format!("{}", CutoffKeytrack::Off), "0%");
        assert_eq!(format!("{}", CutoffKeytrack::Half), "50%");
        assert_eq!(format!("{}", CutoffKeytrack::Full), "100%");
    }

    #[test]
    fn cutoff_drive_display() {
        assert_eq!(format!("{}", CutoffDrive::Off), "0%");
        assert_eq!(format!("{}", CutoffDrive::Half), "50%");
        assert_eq!(format!("{}", CutoffDrive::Full), "100%");
    }

    #[test]
    fn vco_octave_display() {
        assert_eq!(format!("{}", VcoOctave::Sixteen), "16'");
        assert_eq!(format!("{}", VcoOctave::Eight), "8'");
        assert_eq!(format!("{}", VcoOctave::Four), "4'");
        assert_eq!(format!("{}", VcoOctave::Two), "2'");
    }

    // --- Boundary tests for band-based enums ---

    #[test]
    fn sync_rx_boundary() {
        assert_eq!(Sync::from_rx_value(63).unwrap(), Sync::Off);
        assert_eq!(Sync::from_rx_value(64).unwrap(), Sync::On);
    }

    #[test]
    fn vco_wave_rx_boundaries() {
        assert_eq!(VcoWave::from_rx_value(42).unwrap(), VcoWave::Sqr);
        assert_eq!(VcoWave::from_rx_value(43).unwrap(), VcoWave::Tri);
        assert_eq!(VcoWave::from_rx_value(85).unwrap(), VcoWave::Tri);
        assert_eq!(VcoWave::from_rx_value(86).unwrap(), VcoWave::Saw);
    }

    #[test]
    fn vco_octave_rx_boundaries() {
        assert_eq!(VcoOctave::from_rx_value(31).unwrap(), VcoOctave::Sixteen);
        assert_eq!(VcoOctave::from_rx_value(32).unwrap(), VcoOctave::Eight);
        assert_eq!(VcoOctave::from_rx_value(63).unwrap(), VcoOctave::Eight);
        assert_eq!(VcoOctave::from_rx_value(64).unwrap(), VcoOctave::Four);
        assert_eq!(VcoOctave::from_rx_value(95).unwrap(), VcoOctave::Four);
        assert_eq!(VcoOctave::from_rx_value(96).unwrap(), VcoOctave::Two);
    }

    #[test]
    fn delay_sub_type_rx_boundaries() {
        // First/last boundaries
        assert_eq!(
            DelaySubType::from_rx_value(0).unwrap(),
            DelaySubType::Stereo
        );
        assert_eq!(
            DelaySubType::from_rx_value(6).unwrap(),
            DelaySubType::Stereo
        );
        assert_eq!(DelaySubType::from_rx_value(7).unwrap(), DelaySubType::Mono);
        assert_eq!(
            DelaySubType::from_rx_value(127).unwrap(),
            DelaySubType::User8
        );
        assert_eq!(
            DelaySubType::from_rx_value(122).unwrap(),
            DelaySubType::User8
        );
    }

    #[test]
    fn reverb_sub_type_rx_boundaries() {
        assert_eq!(
            ReverbSubType::from_rx_value(0).unwrap(),
            ReverbSubType::Hall
        );
        assert_eq!(
            ReverbSubType::from_rx_value(7).unwrap(),
            ReverbSubType::Hall
        );
        assert_eq!(
            ReverbSubType::from_rx_value(8).unwrap(),
            ReverbSubType::Smooth
        );
        assert_eq!(
            ReverbSubType::from_rx_value(127).unwrap(),
            ReverbSubType::User8
        );
        assert_eq!(
            ReverbSubType::from_rx_value(121).unwrap(),
            ReverbSubType::User8
        );
    }

    #[test]
    fn mod_fx_sub_type_chorus_rx_boundaries() {
        assert_eq!(
            ModFxSubTypeChorus::from_rx_value(15).unwrap(),
            ModFxSubTypeChorus::Stereo
        );
        assert_eq!(
            ModFxSubTypeChorus::from_rx_value(16).unwrap(),
            ModFxSubTypeChorus::Light
        );
        assert_eq!(
            ModFxSubTypeChorus::from_rx_value(112).unwrap(),
            ModFxSubTypeChorus::Vibrato
        );
        assert_eq!(
            ModFxSubTypeChorus::from_rx_value(127).unwrap(),
            ModFxSubTypeChorus::Vibrato
        );
    }
}
